### PR TITLE
Particle - merge 

### PR DESCRIPTION
**Pull request by ananthnayak2000**
Draft pull Request ?

### CODE REVIEW

**Review by zaneliu94 — APPROVED** [review]
'APPROVE' performed by Xcode.

**Comment by couzteau** [comment]
Hmm, I can see your idea and I like it. Unfortunately you branch was not in a clean state, i.e. in sync with main when you started to make changes. Looks like you had my branch and then added changes. That makes it a little tricky to see what you actually changed. I'll take a look and see if I can untangle the different threads.

**Comment by couzteau** [comment]
There is a resolve conflicts button above. Don't use that, please! It will likely break the project. The conflicts have to be resolved in Xcode and to make sure we don't break anything.

**Comment by couzteau** [comment]
It's tough to untangle.

**Comment by couzteau** [comment]
I have extracted the parts from this PR that add the new emitter and merged it with main. Reverted all of the breaking changes. New PR is here: https://github.com/ananthnayak2000/RainbowSynth/pull/11

This can be closed. Merging it would be harmful

**Pull request closed without merging**
